### ISSUE TITLE
Detected package downgrade Microsoft.Extensions.Logging.Abstractions from 7.0.1 to 7.0.0

### ISSUE THREAD

**Issue by toumir** [fluxera/Fluxera.Repository#103]
**Description** 
I'm using Fluxera.Repository.LiteDB version 7.2.3 if a try to Updgrade to the latest version 7.2.5 I get this error and the upgrade won't work : 

```NU1605: Warning As Error: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 7.0.1 to 7.0.0. Reference the package directly from the project to select a different version. 
 <<ProjectName>> -> Fluxera.Repository.LiteDB 7.2.5 -> Fluxera.Repository 7.2.5 -> Fluxera.Repository.Abstractions 7.2.5 -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.1) 
 <<ProjectName>> -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.0)
```

**Steps to Reproduce:**
Create a new Maui.net application
Add the latest Fluxera.Repository.LiteDB 7.2.5 to the project

**Expected Behavior**
The package should be installed without a problem

**Actual Behavior**
The error Above 

**Basic Information**
The version  7.2.3  can be  installed without any problem

**Comment by mgernand** [comment]
Thanks for bringing this to my attention. Will look into it asap.

**Comment by toumir** [comment]
@mgernand  I think the problem **is not solved yet**, to reproduce the issue, Juste create a blank .net maui app then add the latest version of the Fluxera.Repository.LiteDB package  you will get this error : 
```NU1605: Warning As Error: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 7.0.1 to 7.0.0. Reference the package directly from the project to select a different version. ```

Thanks for the quick reply ,for the following and for the great library you shared  😄

**Comment by toumir** [comment]
The Fix performs well when targeting .NET MAUI 8 preview 👍
