### ISSUE TITLE
Entity Framework owned entities not saving

### ISSUE THREAD

**Issue by roly445** [fluxera/Fluxera.Repository#105]
Hi, I have just started looking into using this framework to accelerate my development around DDD.

I am currently using EF core and owned entities and I'm having issues with the persistence on these types.

I have used Rider to debug into the assembly as it's running and found that if I force the skipping the method `PrepareItem` in `EntityFrameworkCoreRepository`  it works as expected.

Do you have any guidance on this?

Many thanks

**Comment by mgernand** [comment]
Hi, thanks for bringing this to our attention. Can you post your repository and EF Core configuration? Or do you have an example app that  we can look at?

**Comment by roly445** [comment]
I have something; just let me get it in a reasonable state and I'll send you a link to the repository.

**Comment by roly445** [comment]
I have just tidied up the solution and uploaded it here https://github.com/roly445/spamma. Hopefully it makes sense.

**Comment by roly445** [comment]
Would you accept a PR for this?

**Comment by mgernand** [comment]
> Would you accept a PR for this?

Yes, absolutely.

**Comment by roly445** [comment]
Thanks, I will do.  Just so I know, what was the rationale behind modifying the entity's state?

**Comment by mgernand** [comment]
> Just so I know, what was the rationale behind modifying the entity's state?

To be honest, I don't know anymore why I did that. 🙈
