### ISSUE TITLE
[Question]  EntityFramework Core Supported?

### ISSUE THREAD

**Issue by jeffward01** [fluxera/Fluxera.Repository#54]
Hello!

Great library!! I love how you have structured your code - very modular and helpful with the interceptors

**My primary use-case is for Entity Framework Core & MSSQL** 

I saw that you had: `EntityFrameworkRepository` and also saw on your `Readme.md` that:

> Coming soon: EntityFramework Core and OData

## Question

1.) Is Entity Framework Core (latest net7) supported 
    *  Partially?
    *  Fully?
    *  None?

2.) When I saw `EntityFrameworkRepository` I was confused to if this meant `EfCore` or `EntityFramework`  - Can you clarify please?

--------

Thanks all!

**Comment by mgernand** [comment]
Hello!

The current version supports EF Core (v6). Unfortunately the documentation not up to date.

I am currently working on v7 of the library which will include Unit-of-Work support for every storage including EF Core v7, additional samples and (hopefully) better documentation. I hope to finish this up over the weekend.

But to answer your questions:

1. EF Core 6 is fully supported in the v6 branch of the library and EF Core 7 will be in v7 of the library.
2. The ```EntityFrameworkRepository``` actually means EF Core. I'll fix the naming in v7 to avaid this kind of confusion in the future. Thanks for pointing this out.

I hope I could clarify things up a bit. :-) If you have any other questions, ideas or recommendations let me know.

Cheers, Matt

**Comment by jeffward01** [comment]
Thanks for this! This clears things up alot.

I actually am also creating a UnitOfWork implementaton for this - I can create a pull request also when I get it implemented and possibly add features, or use features from your Implementation.

> EF Core 6 is fully supported in the v6 branch of the library and EF Core 7 will be in v7 of the library.

Sounds good, I believe I am using Version 7 of your library (most recent)

Yes this clears things up alot!

----

Off-topic: I have been involved in crypto since 2016/17, and launched a few coins professionally for my employers - I saw you are also!! Very cool!! Few points I have to give you a hard time 😄  =>

* Cardano is AWESOME except:
    *  Haskell is gross
    * The team moves sooo slow - not sure if its realistic for them to deliver a functioning chain 
    * The coin is large enough in $$ (trading volume) that it will never go away
    * The community is so engrossed in 'voting' that they never get anything done that can help 'real enterprise chains'
    * The language is so gross - that its painful to build a functioning application (Algorand also had this issue)

* Bitcoin Cash is the real king 🙃 

Also - I am surprised your not a big supporter of Neo! Why Cardano in comparison to Neo? The Neo tech v3 has more features than IPFS and very good smart contracts, good tech -- its China - Fair  Point - but the tech is amazing

---

Very cool to meet you

**Comment by mgernand** [comment]
Hi Jeff,

I published v7.0 yesterday. If you like you can have a look at the UoW implementation for EFCore 7.
I needed to jump through some hoops, because I allow to have multiple repositories with different configurations in a single application. But I am fine with how it turned out.

----

Off-topic:

- Cardano is AWESOME
    - I agree that it is. 😉
    - I too agree that Haskell/Plutus is painful to work with. But Haskell fits the academic approach and the formal verfication of code. This discussion is widly held within the communitiy. Maybe we see other langages for smart contracts in the future. Would be cool to write them in C#.
    - I really hope it will stay for a long time. Not only because I invested in it, but because I really believe this is right way to appoach projects of this magnitude.
    - I think the self convernance of the chain is a major step to true decentralization. But I agree that Cardano is not seen as an "enterprise chain". I hope this will happen over time.
    - I agree that the language is gross, but maybe it leads to evelopers coding more carfully. There are a lot projects already running their contracts and a lot projects in the making. But this needs to be monitored for sure.
    - After last weeks FTX armageddon I am more certain that Cardano has a very strong selling point in decentrelization and escpecially their liquid staking. As you know: Not your keys, not your coins.😉

- Bitcoin is the real Slim Shady 😄

I hope you haven't lost anything in the FTX debacle.

----

Cool to meet you too

Matt

**Comment by jeffward01** [comment]
Haha, Bitcoin is the real slim shady touche' - and also BCH has so many shady characters involved, BTC also.  You are correct. Cardano is the sophisticated slow moving genius who will do great things!

Cardano is great, I agree with you on all points, I really hope to see it rise and get some more attention, I think this will be the case once the technology is more mature and can be confidently used by enterprise level companies.

**C# and blockchain:**

My personal favorite is NEO, but because USA is generally untrusting of chinese software, I don't think it will ever 'rise' in usage in mainstream software.

Stratis development is so slow, and just not very advanced, very small community - i think its interesting and was my favorite chain in 2016/17, but I just don't see it making a big impact on the industry. I hope I am wrong on this, there are some excellent C# developers who are active on github, who worked on Stratis. You can find the developers in most any C# Bitcoin repository.
